### ISSUE TITLE
Onboarding link generation broken with v3 update

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#100]
I've upgraded to v3.0.1 in our dev environment and we are now seeing that the onboarding links for Stripe Connect are no longer being generated.

Logs we get are:

```
{"message":"Could not create Stripe AccountLink: Not a valid URL.","context":{"shopId":2093,"accountId":"xxxxx","stripeErrorCode":"url_invalid"},"level":400,"level_name":"ERROR","channel":"onboarding","datetime":{"date":"2022-03-16 01:01:46.628158","timezone_type":3,"timezone":"UTC"},"extra":[]}
```

We didn't change any other settings with a working setup on v2.1.4. Are the arguments being passed to the Stripe Client call correct?

**Comment by christophersjchow** [comment]
Ok it looks like I had `BASE_HOST` configured as a URL `https://stripe-host/` instead of just a raw hostname causing the URL that was generated to include `https://https://` at the beginning.

I can't remember if the old docs referenced this env var with http or not but maybe a good to add to the changelog.

The other thing to add to the change log is to update the connect settings to disable the OAuth redirect.

**Comment by christophersjchow** [comment]
Oh another big change in behaviour is that any time a store is created in Mirakl, a connect account is created in Stripe whereas before the account would never appear until the onboarding was done.

Not a huge deal but another change in behaviour.

**Comment by youssef-stripe** [comment]
>I can't remember if the old docs referenced this env var with http or not but maybe a good to add to the changelog.

`BASE_HOST` was indeed incorrectly documented with an example starting with the scheme (https://). Still, Symfony always expected this value to be without the scheme. Before version 3, this wouldn't trigger an exception because the URL was passed as a query parameter and Stripe would default to the set Oauth URL in the Dashboard if the passed URL was incorrect.

>The other thing to add to the change log is to update the connect settings to disable the OAuth redirect.

That's optional but still worth mentioning I agree.

>Oh another big change in behaviour is that any time a store is created in Mirakl, a connect account is created in Stripe whereas before the account would never appear until the onboarding was done.

This is mentioned in the changelog `Stripe accounts are now created during the onboarding job and mapped with the corresponding Mirakl shop.`
