### ISSUE TITLE
v2 beta: Are invoices meant to be marked as paid

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#63]
I notice that the connector doesn't seem to close the loop on invoices and leaves them in a pending status. Is this an intentional gap for some reason? Or is it something is just yet to be built?

**Comment by youssef-stripe** [comment]
At the moment we don't mark invoices as "paid" because creating the payout isn't confirmation enough that the funds will indeed reach the seller's bank account. Ideally we would mark the invoice as "paid" and later change the status if there is a failure but Mirakl doesn't support failed statuses for invoices yet.

So I'll close this for now as we are limited by the current invoice workflow on Mirakl. Happy to revisit once we have more granularity on invoice statuses.

In the meantime, you can listen to payout.created or some other event to mark the invoice as paid or have the seller confirm the payout manually via your interface.
