### ISSUE TITLE
OutOfMemoryError while executing connector:dispatch:process-transfer

### ISSUE THREAD

**Issue by eBusEntwHOFM** [stripe/stripe-mirakl-connector#67]
Hi there,

on our staging environment we have > 17.700 orders, because of integration tests. Looks like `connector:dispatch:process-transfer` cann't handle this number of orders using 134M ram. Indeed it is a quite unusual number, but it looks for me, that we have either a memory leak somewhere or not efficient handling.

```
time="2021-02-20T17:38:41Z" level=info msg="{\"message\":\"Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 266240 bytes)\",\"context\":{\"exception\":{\"class\":\"Symfony\\\\Component\\\\ErrorHandler\\\\Error\\\\OutOfMemoryError\",\"message\":\"Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 266240 bytes)\",\"code\":0,\"file\":\"/var/www/src/Service/MiraklClient.php:63\"}},\"level\":500,\"level_name\":\"CRITICAL\",\"channel\":\"php\",\"datetime\":{\"date\":\"2021-02-20 17:38:41.850659\",\"timezone_type\":3,\"timezone\":\"UTC\"},\"extra\":[]}" channel=stdout iteration=257 job.command="php /var/www/bin/console connector:dispatch:process-transfer -q 2>&1" job.position=2 job.schedule="1-59/5  *       *   *       *"
```
It loops also always over all orders regardless whether they were already checked once in the last run.

Best regards

**Comment by youssef-stripe** [comment]
We made some performance improvements in v2.0.2.
Still, this job is supposed to run every 5 minutes so it shouldn't have to handle > 10,000 orders in a single run (neither is it  designed for it).

The problem occurs when running the first time as it will go over all the existing orders since the Mirakl environment was created. To avoid that, you can update/insert the `product_payment_split_checkpoint` key in the config table and set the value to a recent date that you can choose based on when the orders are meant to be processed by the connector.

We will make this process easier in the future, i.e. be able to set a date when installing the connector for the first time for existing Mirakl users migrating to our connector (or upgrading from v1 to v2).
